import type { BrewMethod } from '../types/recipe.ts';
import type { EquipmentType } from '../types/equipment.ts';

export interface BrewMethodEquipmentRuleDef {
  brewMethod: BrewMethod;
  equipmentType: EquipmentType;
  compatible: boolean;
}

export const EQUIPMENT_TYPES: EquipmentType[] = [
  'espresso_machine',
  'grinder',
  'pour_over_brewer',
  'immersion_brewer',
  'kettle',
  'milk_tool',
  'scale_accessory',
  'roaster',
  'portafilter',
  'basket',
  'puck_screen',
  'paper_filter',
  'tamper',
  'mesh_filter',
  'cezve',
  'thermometer',
  'other',
];

export const EQUIPMENT_TYPE_LABELS: Record<EquipmentType, string> = {
  espresso_machine: 'Espresso Machine',
  grinder: 'Grinder',
  pour_over_brewer: 'Pour-Over & Filter Brewer',
  immersion_brewer: 'Immersion & Pressure Brewer',
  kettle: 'Kettle',
  milk_tool: 'Milk Tool',
  scale_accessory: 'Scale & Accessory',
  roaster: 'Roaster',
  portafilter: 'Portafilter',
  basket: 'Basket',
  puck_screen: 'Puck Screen',
  paper_filter: 'Paper Filter',
  tamper: 'Tamper',
  mesh_filter: 'Mesh Filter',
  cezve: 'Cezve',
  thermometer: 'Thermometer',
  other: 'Other',
};

export const BREW_METHOD_EQUIPMENT_RULES: BrewMethodEquipmentRuleDef[] = [
  { brewMethod: 'espresso_machine', equipmentType: 'espresso_machine', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'grinder', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'portafilter', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'basket', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'tamper', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'puck_screen', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'paper_filter', compatible: false },
  { brewMethod: 'espresso_machine', equipmentType: 'mesh_filter', compatible: false },
  { brewMethod: 'v60', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'v60', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'v60', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'v60', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'v60', equipmentType: 'portafilter', compatible: false },
  { brewMethod: 'v60', equipmentType: 'tamper', compatible: false },
  { brewMethod: 'french_press', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'mesh_filter', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'turkish_coffee', equipmentType: 'cezve', compatible: true },
  { brewMethod: 'turkish_coffee', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'moka_pot', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'moka_pot', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'mesh_filter', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'thermometer', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'kettle', compatible: true },
];
