import { hashSync } from 'bcryptjs';

export function hashPassword(password: string): string {
  return hashSync(password, 10);
}

export const defaultPassword = 'user123456';

export const badgeSeedData = [
  {
    name: 'First Brew',
    icon: 'coffee',
    rule: 'first_brew' as const,
    description: 'Logged your first recipe',
    threshold: 1,
  },
  {
    name: 'Decade Brewer',
    icon: 'ten',
    rule: 'decade_brewer' as const,
    description: '10 recipes logged',
    threshold: 10,
  },
  {
    name: 'Centurion',
    icon: '100',
    rule: 'centurion' as const,
    description: '100 recipes logged',
    threshold: 100,
  },
  {
    name: 'First Fork',
    icon: 'fork_and_knife',
    rule: 'first_fork' as const,
    description: 'Forked your first recipe',
    threshold: 1,
  },
  {
    name: 'Fan Favourite',
    icon: 'star',
    rule: 'fan_favourite' as const,
    description: 'One of your recipes received 10+ likes',
    threshold: 10,
  },
  {
    name: 'Community Star',
    icon: 'star2',
    rule: 'community_star' as const,
    description: 'One of your recipes received 50+ likes',
    threshold: 50,
  },
  {
    name: 'Conversationalist',
    icon: 'speech_balloon',
    rule: 'conversationalist' as const,
    description: 'Left 10+ comments',
    threshold: 10,
  },
  {
    name: 'Precision Brewer',
    icon: 'dart',
    rule: 'precision_brewer' as const,
    description: 'Logged 10 recipes with all optional fields filled',
    threshold: 10,
  },
  {
    name: 'Explorer',
    icon: 'globe',
    rule: 'explorer' as const,
    description: 'Brewed with 5+ different brew methods',
    threshold: 5,
  },
  {
    name: 'Influencer',
    icon: 'busts_in_silhouette',
    rule: 'influencer' as const,
    description: 'Gained 25+ followers',
    threshold: 25,
  },
];

export const brewMethodCompatibilityRules: Array<{
  brewMethod: string;
  equipmentType: string;
  compatible: boolean;
}> = [
  { brewMethod: 'espresso_machine', equipmentType: 'portafilter', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'basket', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'tamper', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'puck_screen', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'scale', compatible: true },
  { brewMethod: 'v60', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'v60', equipmentType: 'gooseneck_kettle', compatible: true },
  { brewMethod: 'v60', equipmentType: 'scale', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'mesh_filter', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'scale', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'scale', compatible: true },
  { brewMethod: 'turkish_coffee', equipmentType: 'cezve', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'scale', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'gooseneck_kettle', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'scale', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'gooseneck_kettle', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'scale', compatible: true },
  { brewMethod: 'moka_pot', equipmentType: 'scale', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'mesh_filter', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'scale', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'scale', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'thermometer', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'paper_filter', compatible: false },
  { brewMethod: 'espresso_machine', equipmentType: 'mesh_filter', compatible: false },
  { brewMethod: 'espresso_machine', equipmentType: 'gooseneck_kettle', compatible: false },
  { brewMethod: 'v60', equipmentType: 'portafilter', compatible: false },
  { brewMethod: 'v60', equipmentType: 'tamper', compatible: false },
  { brewMethod: 'turkish_coffee', equipmentType: 'portafilter', compatible: false },
];

export const userSeedData = [
  {
    email: 'alice@example.com',
    username: 'alice',
    displayName: 'Alice Brewer',
    bio: 'Espresso enthusiast from Portland',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'coffee' },
  },
  {
    email: 'bob@example.com',
    username: 'bob',
    displayName: 'Bob Barista',
    bio: 'V60 lover and specialty coffee nerd',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'dark' },
  },
  {
    email: 'charlie@example.com',
    username: 'charlie',
    displayName: 'Charlie Press',
    bio: 'French press aficionado from Seattle',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'coffee' },
  },
  {
    email: 'diana@example.com',
    username: 'diana',
    displayName: 'Diana Turkish',
    bio: 'Traditional coffee lover from Istanbul',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'dark' },
  },
  {
    email: 'evan@example.com',
    username: 'evan',
    displayName: 'Evan ColdBrew',
    bio: 'Specialty coffee experimenter',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'light' },
  },
];

export const equipmentSeedData = [
  {
    name: 'Bottomless Portafilter 58mm',
    type: 'portafilter',
    brand: 'Lelit',
    createdByUsername: 'alice',
  },
  {
    name: 'IMS H24 18g',
    type: 'basket',
    brand: 'IMS',
    createdByUsername: 'alice',
  },
  {
    name: 'Normcore 58.5mm Spring Tamper',
    type: 'tamper',
    brand: 'Normcore',
    createdByUsername: 'alice',
  },
  {
    name: 'Metal Puck Screen 58.5mm',
    type: 'puck_screen',
    brand: 'Sieve',
    createdByUsername: 'alice',
  },
  {
    name: 'Fellow Stagg EKG',
    type: 'gooseneck_kettle',
    brand: 'Fellow',
    createdByUsername: 'bob',
  },
  {
    name: 'Hario V60 Paper Filter 02',
    type: 'paper_filter',
    brand: 'Hario',
    createdByUsername: 'bob',
  },
  {
    name: 'Acaia Lunar',
    type: 'scale',
    brand: 'Acaia',
    description: 'High-precision espresso scale',
    createdByUsername: 'alice',
  },
  {
    name: 'Bodum Chambord French Press',
    type: 'mesh_filter',
    brand: 'Bodum',
    description: 'Classic 8-cup French press',
    createdByUsername: 'charlie',
  },
  {
    name: 'Beko Turkish Coffee Pot',
    type: 'cezve',
    brand: 'Beko',
    description: 'Electric copper cezve',
    createdByUsername: 'diana',
  },
  {
    name: 'Hario Drip Scale',
    type: 'scale',
    brand: 'Hario',
    description: 'Pour-over scale with timer',
    createdByUsername: 'evan',
  },
];

export const vendorSeedData = [
  {
    name: 'Heart Coffee Roasters',
    website: 'https://heartroasters.com',
    description: 'Portland-based specialty coffee roaster',
  },
  {
    name: 'Counter Culture Coffee',
    website: 'https://counterculturecoffee.com',
    description: 'Durham-based sustainable roaster',
  },
  {
    name: 'Kurukahveci Mehmet Efendi',
    website: 'https://mehmetefendi.com',
    description: 'Historic Turkish coffee roaster from Istanbul',
  },
];

export const beanSeedData = [
  {
    name: 'Heart Ethiopia Yirgacheffe',
    brand: 'Heart',
    vendorName: 'Heart Coffee Roasters',
    roaster: 'Heart Coffee Roasters',
    roastLevel: 'light',
    processing: 'washed',
    origin: 'Ethiopia, Yirgacheffe',
    userUsername: 'alice',
  },
  {
    name: 'Counter Culture Big Trouble',
    brand: 'Counter Culture',
    vendorName: 'Counter Culture Coffee',
    roaster: 'Counter Culture Coffee',
    roastLevel: 'medium',
    processing: 'natural',
    origin: 'Brazil, Minas Gerais',
    userUsername: 'charlie',
  },
  {
    name: 'Mehmet Efendi Turkish Blend',
    brand: 'Mehmet Efendi',
    vendorName: 'Kurukahveci Mehmet Efendi',
    roaster: 'Kurukahveci Mehmet Efendi',
    roastLevel: 'dark',
    processing: 'washed',
    origin: 'Turkey, Brazil blend',
    userUsername: 'diana',
  },
  {
    name: 'Counter Culture Fast Forward',
    brand: 'Counter Culture',
    vendorName: 'Counter Culture Coffee',
    roaster: 'Counter Culture Coffee',
    roastLevel: 'medium',
    processing: 'washed',
    origin: 'Colombia, Huila',
    userUsername: 'evan',
  },
];

export const recipeSeedData = [
  {
    slug: 'alices-signature-espresso',
    title: "Alice's Signature Espresso",
    authorUsername: 'alice',
    visibility: 'public',
    likeCount: 5,
    commentCount: 2,
    forkCount: 1,
    featured: true,
    version: {
      productName: 'Heart Ethiopia Yirgacheffe',
      coffeeBrand: 'Heart',
      coffeeProcessing: 'washed',
      vendorName: 'Heart Coffee Roasters',
      roastDate: '2026-03-15',
      packageOpenDate: '2026-04-01',
      grindDate: '2026-04-10',
      brewDate: '2026-04-15',
      brewMethod: 'espresso_machine',
      drinkType: 'espresso',
      brewerDetails: 'Lelit Mara X',
      grinder: 'Lelit Fred',
      grindSize: '12',
      groundWeightGrams: 18,
      extractionTimeSeconds: 28,
      preInfusionTimeSeconds: 5,
      extractionVolumeMl: 36,
      temperatureCelsius: 93,
      tds: 9.5,
      brewRatio: 2.0,
      flowRate: 1.29,
      personalNotes: 'Beautiful sweet shot with floral notes and a honey finish.',
      preparationNotes:
        '1. Preheat the machine and portafilter for 10 minutes.\n2. Dose 18g of coffee into the basket.\n3. Distribute evenly and tamp with 15kg pressure.\n4. Lock in the portafilter and start extraction immediately.\n5. Aim for 36g out in 25-30 seconds.\n6. Serve in a preheated cup.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Normcore 58.5mm Spring Tamper',
      'Metal Puck Screen 58.5mm',
      'Acaia Lunar',
    ],
    tasteNotes: [
      { name: 'Raspberry', intensity: 2 },
      { name: 'Dark chocolate', intensity: 3 },
      { name: 'Rose', intensity: 1 },
      { name: 'Caramelized', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefad?w=800',
        alt: 'Espresso shot with crema',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'bobs-morning-v60',
    title: "Bob's Morning V60",
    authorUsername: 'bob',
    visibility: 'public',
    likeCount: 3,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Heart Ethiopia Yirgacheffe',
      coffeeBrand: 'Heart',
      coffeeProcessing: 'washed',
      vendorName: 'Heart Coffee Roasters',
      roastDate: '2026-03-15',
      packageOpenDate: '2026-03-22',
      grindDate: '2026-04-12',
      brewDate: '2026-04-12',
      brewMethod: 'v60',
      drinkType: 'pour_over',
      brewerDetails: 'Hario V60 02',
      grinder: 'Baratza Encore',
      grindSize: '20',
      groundWeightGrams: 15,
      extractionTimeSeconds: 210,
      extractionVolumeMl: 250,
      temperatureCelsius: 96,
      tds: 1.35,
      brewRatio: 16.67,
      flowRate: 1.19,
      personalNotes: 'Clean, bright cup. Great morning brew.',
      preparationNotes:
        '1. Rinse the paper filter with hot water and discard.\n2. Add 15g of medium-fine ground coffee.\n3. Bloom with 30g water for 30 seconds.\n4. Pour remaining water in slow circles to 250g total.\n5. Let drain completely.\n6. Serve immediately.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'rocket',
    },
    equipmentNames: ['Fellow Stagg EKG', 'Hario V60 Paper Filter 02'],
    tasteNotes: [
      { name: 'Jasmine', intensity: 2 },
      { name: 'Cinnamon', intensity: 3 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        alt: 'V60 pour over',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'charlies-french-press-classic',
    title: "Charlie's French Press Classic",
    authorUsername: 'charlie',
    visibility: 'public',
    likeCount: 4,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Counter Culture Big Trouble',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'natural',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-02-10',
      packageOpenDate: '2026-02-20',
      grindDate: '2026-04-05',
      brewDate: '2026-04-05',
      brewMethod: 'french_press',
      drinkType: 'french_press',
      brewerDetails: 'Bodum Chambord 8-cup',
      grinder: 'Comandante C40',
      grindSize: '28',
      groundWeightGrams: 30,
      extractionTimeSeconds: 240,
      extractionVolumeMl: 500,
      temperatureCelsius: 94,
      brewRatio: 16.67,
      flowRate: 2.08,
      personalNotes: 'Full-bodied, rich cup with chocolatey depth.',
      preparationNotes:
        '1. Preheat the press with hot water.\n2. Add 30g coarse ground coffee.\n3. Pour 500ml water at 94C.\n4. Stir gently and place lid without pressing.\n5. Steep for 4 minutes.\n6. Press slowly and serve.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'thumbsup',
    },
    equipmentNames: ['Bodum Chambord French Press', 'Acaia Lunar'],
    tasteNotes: [
      { name: 'Dark chocolate', intensity: 3 },
      { name: 'Hazelnut', intensity: 2 },
      { name: 'Honey', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
        alt: 'French press coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'dianas-turkish-delight',
    title: "Diana's Turkish Delight",
    authorUsername: 'diana',
    visibility: 'public',
    likeCount: 6,
    commentCount: 2,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Mehmet Efendi Turkish Blend',
      coffeeBrand: 'Mehmet Efendi',
      coffeeProcessing: 'washed',
      vendorName: 'Kurukahveci Mehmet Efendi',
      roastDate: '2026-01-15',
      packageOpenDate: '2026-02-01',
      grindDate: '2026-04-08',
      brewDate: '2026-04-08',
      brewMethod: 'turkish_coffee',
      drinkType: 'turkish_coffee',
      brewerDetails: 'Beko Electric Cezve',
      grinder: 'Manual Turkish Grinder',
      grindSize: 'powder',
      groundWeightGrams: 10,
      extractionTimeSeconds: 180,
      extractionVolumeMl: 80,
      temperatureCelsius: 88,
      brewRatio: 8.0,
      flowRate: 0.44,
      personalNotes: 'Rich, thick foam. Best enjoyed with a piece of Turkish delight.',
      preparationNotes:
        '1. Add 10g finely ground coffee and 80ml cold water to cezve.\n2. Add sugar to taste if desired.\n3. Stir well before heating.\n4. Heat slowly over low flame.\n5. Remove just before boiling when foam rises.\n6. Pour into a small cup and let grounds settle.',
      isFavourite: true,
      rating: 10,
      emojiTag: 'fire',
    },
    equipmentNames: ['Beko Turkish Coffee Pot', 'Hario Drip Scale'],
    tasteNotes: [
      { name: 'Clove', intensity: 3 },
      { name: 'Cinnamon', intensity: 2 },
      { name: 'Tobacco', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        alt: 'Turkish coffee in cezve',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'evans-iced-latte',
    title: "Evan's Iced Latte",
    authorUsername: 'evan',
    visibility: 'public',
    likeCount: 7,
    commentCount: 1,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Counter Culture Fast Forward',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'washed',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-03-01',
      packageOpenDate: '2026-03-10',
      grindDate: '2026-04-10',
      brewDate: '2026-04-10',
      brewMethod: 'espresso_machine',
      drinkType: 'latte',
      brewerDetails: 'Breville Barista Express',
      grinder: 'Built-in conical burr',
      grindSize: '15',
      groundWeightGrams: 18,
      extractionTimeSeconds: 25,
      extractionVolumeMl: 36,
      temperatureCelsius: 92,
      brewRatio: 2.0,
      flowRate: 1.44,
      personalNotes: 'Refreshing summer drink with smooth espresso and cold milk over ice.',
      preparationNotes:
        '1. Fill a tall glass with ice cubes.\n2. Pull a double espresso shot (18g in, 36g out).\n3. Pour 200ml cold whole milk over the ice.\n4. Pour the hot espresso over the milk.\n5. Stir gently and serve with a straw.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'rocket',
    },
    equipmentNames: ['Acaia Lunar'],
    additionalPreparations: [
      {
        name: 'Whole milk',
        type: 'milk',
        inputAmount: '200ml',
        preparationType: 'cold',
        sortOrder: 0,
      },
    ],
    tasteNotes: [
      { name: 'Vanilla', intensity: 2 },
      { name: 'Caramelized', intensity: 2 },
      { name: 'Dark chocolate', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
        alt: 'Iced latte in glass',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'evans-affogato',
    title: "Evan's Affogato",
    authorUsername: 'evan',
    visibility: 'public',
    likeCount: 8,
    commentCount: 2,
    forkCount: 1,
    featured: true,
    version: {
      productName: 'Counter Culture Fast Forward',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'washed',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-03-01',
      packageOpenDate: '2026-03-10',
      grindDate: '2026-04-11',
      brewDate: '2026-04-11',
      brewMethod: 'espresso_machine',
      drinkType: 'espresso',
      brewerDetails: 'Breville Barista Express',
      grinder: 'Built-in conical burr',
      grindSize: '14',
      groundWeightGrams: 18,
      extractionTimeSeconds: 26,
      extractionVolumeMl: 36,
      temperatureCelsius: 93,
      brewRatio: 2.0,
      flowRate: 1.38,
      personalNotes: 'Heavenly combination of hot espresso and cold vanilla ice cream.',
      preparationNotes:
        '1. Place one scoop of vanilla ice cream in a small bowl.\n2. Pull a fresh espresso shot (18g in, 36g out).\n3. Pour the hot espresso directly over the ice cream.\n4. Serve immediately with a small spoon.',
      isFavourite: true,
      rating: 10,
      emojiTag: 'fire',
    },
    equipmentNames: ['Acaia Lunar'],
    additionalPreparations: [
      {
        name: 'Vanilla ice cream',
        type: 'other',
        inputAmount: '1 scoop',
        preparationType: 'cold',
        sortOrder: 0,
      },
    ],
    tasteNotes: [
      { name: 'Vanilla', intensity: 3 },
      { name: 'Caramelized', intensity: 2 },
      { name: 'Dark chocolate', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800',
        alt: 'Affogato with ice cream',
        sortOrder: 0,
      },
    ],
  },
];

export const socialSeedData = {
  follows: [
    { followerUsername: 'bob', followingUsername: 'alice' },
    { followerUsername: 'charlie', followingUsername: 'alice' },
    { followerUsername: 'charlie', followingUsername: 'bob' },
    { followerUsername: 'diana', followingUsername: 'alice' },
    { followerUsername: 'diana', followingUsername: 'evan' },
    { followerUsername: 'evan', followingUsername: 'diana' },
    { followerUsername: 'alice', followingUsername: 'evan' },
  ],
  likes: [
    { userUsername: 'bob', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'charlie', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'charlie', recipeSlug: 'bobs-morning-v60' },
    { userUsername: 'diana', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'diana', recipeSlug: 'charlies-french-press-classic' },
    { userUsername: 'evan', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'evan', recipeSlug: 'dianas-turkish-delight' },
    { userUsername: 'alice', recipeSlug: 'evans-iced-latte' },
    { userUsername: 'bob', recipeSlug: 'evans-affogato' },
    { userUsername: 'diana', recipeSlug: 'evans-affogato' },
  ],
  favourites: [
    { userUsername: 'bob', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'charlie', recipeSlug: 'bobs-morning-v60' },
    { userUsername: 'diana', recipeSlug: 'charlies-french-press-classic' },
    { userUsername: 'evan', recipeSlug: 'dianas-turkish-delight' },
    { userUsername: 'alice', recipeSlug: 'evans-iced-latte' },
  ],
  ratings: [
    { userUsername: 'bob', recipeSlug: 'alices-signature-espresso', rating: 9 },
    { userUsername: 'charlie', recipeSlug: 'bobs-morning-v60', rating: 8 },
    { userUsername: 'diana', recipeSlug: 'charlies-french-press-classic', rating: 8 },
    { userUsername: 'evan', recipeSlug: 'dianas-turkish-delight', rating: 10 },
    { userUsername: 'alice', recipeSlug: 'evans-iced-latte', rating: 9 },
    { userUsername: 'bob', recipeSlug: 'evans-affogato', rating: 10 },
  ],
  comments: [
    {
      recipeSlug: 'alices-signature-espresso',
      authorUsername: 'bob',
      content: 'Amazing shot! What grinder setting are you using?',
      replies: [
        { authorUsername: 'alice', content: 'Thanks! Setting 12 on the Lelit Fred.' },
      ],
    },
    {
      recipeSlug: 'charlies-french-press-classic',
      authorUsername: 'diana',
      content: 'Love the full body of this method!',
      replies: [],
    },
    {
      recipeSlug: 'dianas-turkish-delight',
      authorUsername: 'evan',
      content: 'The foam is incredible. What sugar ratio do you use?',
      replies: [
        {
          authorUsername: 'diana',
          content: 'I prefer it unsweetened, but 1 tsp per cup is traditional.',
        },
      ],
    },
    {
      recipeSlug: 'evans-affogato',
      authorUsername: 'alice',
      content: 'This is my new favourite dessert coffee!',
      replies: [
        {
          authorUsername: 'evan',
          content: 'Glad you like it! Try it with caramel drizzle next time.',
        },
      ],
    },
  ],
  badges: [
    { userUsername: 'alice', badgeRule: 'first_brew' },
    { userUsername: 'bob', badgeRule: 'first_brew' },
    { userUsername: 'charlie', badgeRule: 'first_brew' },
    { userUsername: 'diana', badgeRule: 'first_brew' },
    { userUsername: 'evan', badgeRule: 'first_brew' },
  ],
};

export const setupSeedData = [
  {
    name: "Alice's Espresso Setup",
    userUsername: 'alice',
    brewerDetails: 'Lelit Mara X',
    grinder: 'Lelit Fred',
    equipmentNames: [
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Metal Puck Screen 58.5mm',
      'Normcore 58.5mm Spring Tamper',
    ],
    isDefault: true,
  },
  {
    name: "Bob's V60 Setup",
    userUsername: 'bob',
    brewerDetails: 'Hario V60 02',
    grinder: 'Baratza Encore',
    equipmentNames: [],
    isDefault: true,
  },
  {
    name: "Charlie's French Press Setup",
    userUsername: 'charlie',
    brewerDetails: 'Bodum Chambord 8-cup',
    grinder: 'Comandante C40',
    equipmentNames: ['Bodum Chambord French Press'],
    isDefault: true,
  },
  {
    name: "Diana's Turkish Setup",
    userUsername: 'diana',
    brewerDetails: 'Beko Electric Cezve',
    grinder: 'Manual Turkish Grinder',
    equipmentNames: ['Beko Turkish Coffee Pot'],
    isDefault: true,
  },
  {
    name: "Evan's Espresso Setup",
    userUsername: 'evan',
    brewerDetails: 'Breville Barista Express',
    grinder: 'Built-in conical burr',
    equipmentNames: [],
    isDefault: true,
  },
];
