import { hashSync } from 'bcryptjs';

/** Hashes a plaintext password with bcrypt (cost 10, synchronous) for seed-user rows. */
export function hashPassword(password: string): string {
  return hashSync(password, 10);
}

/** Shared plaintext password for all non-admin seed users. */
export const defaultPassword = 'user123456';

/** Badge definitions seeded into the `badge` table. */
export const badgeSeedData = [
  {
    name: 'First Brew',
    icon: 'coffee',
    rule: 'first_brew' as const,
    description: 'Logged your first recipe',
    threshold: 1,
  },
  {
    name: 'Decade Brewer',
    icon: 'ten',
    rule: 'decade_brewer' as const,
    description: '10 recipes logged',
    threshold: 10,
  },
  {
    name: 'Centurion',
    icon: '100',
    rule: 'centurion' as const,
    description: '100 recipes logged',
    threshold: 100,
  },
  {
    name: 'First Fork',
    icon: 'fork_and_knife',
    rule: 'first_fork' as const,
    description: 'Forked your first recipe',
    threshold: 1,
  },
  {
    name: 'Fan Favourite',
    icon: 'star',
    rule: 'fan_favourite' as const,
    description: 'One of your recipes received 10+ likes',
    threshold: 10,
  },
  {
    name: 'Community Star',
    icon: 'star2',
    rule: 'community_star' as const,
    description: 'One of your recipes received 50+ likes',
    threshold: 50,
  },
  {
    name: 'Conversationalist',
    icon: 'speech_balloon',
    rule: 'conversationalist' as const,
    description: 'Left 10+ comments',
    threshold: 10,
  },
  {
    name: 'Precision Brewer',
    icon: 'dart',
    rule: 'precision_brewer' as const,
    description: 'Logged 10 recipes with all optional fields filled',
    threshold: 10,
  },
  {
    name: 'Explorer',
    icon: 'globe',
    rule: 'explorer' as const,
    description: 'Brewed with 5+ different brew methods',
    threshold: 5,
  },
  {
    name: 'Influencer',
    icon: 'busts_in_silhouette',
    rule: 'influencer' as const,
    description: 'Gained 25+ followers',
    threshold: 25,
  },
];

/** Brew-method ↔ equipment-type compatibility rows for {@link brewMethodEquipmentRules}. */
export const brewMethodCompatibilityRules: Array<{
  brewMethod: string;
  equipmentType: string;
  compatible: boolean;
}> = [
  // Espresso Machine
  { brewMethod: 'espresso_machine', equipmentType: 'espresso_machine', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'grinder', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'portafilter', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'basket', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'tamper', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'puck_screen', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'espresso_machine', equipmentType: 'paper_filter', compatible: false },
  { brewMethod: 'espresso_machine', equipmentType: 'mesh_filter', compatible: false },
  { brewMethod: 'espresso_machine', equipmentType: 'immersion_brewer', compatible: false },
  // V60
  { brewMethod: 'v60', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'v60', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'v60', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'v60', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'v60', equipmentType: 'portafilter', compatible: false },
  { brewMethod: 'v60', equipmentType: 'tamper', compatible: false },
  // French Press
  { brewMethod: 'french_press', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'mesh_filter', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'french_press', equipmentType: 'grinder', compatible: true },
  // AeroPress
  { brewMethod: 'aeropress', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'aeropress', equipmentType: 'grinder', compatible: true },
  // Turkish Coffee
  { brewMethod: 'turkish_coffee', equipmentType: 'cezve', compatible: true },
  { brewMethod: 'turkish_coffee', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'turkish_coffee', equipmentType: 'grinder', compatible: true },
  { brewMethod: 'turkish_coffee', equipmentType: 'portafilter', compatible: false },
  // Drip Coffee
  { brewMethod: 'drip_coffee', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'drip_coffee', equipmentType: 'grinder', compatible: true },
  // Chemex
  { brewMethod: 'chemex', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'chemex', equipmentType: 'scale_accessory', compatible: true },
  // Kalita Wave
  { brewMethod: 'kalita_wave', equipmentType: 'pour_over_brewer', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'paper_filter', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'kettle', compatible: true },
  { brewMethod: 'kalita_wave', equipmentType: 'scale_accessory', compatible: true },
  // Moka Pot
  { brewMethod: 'moka_pot', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'moka_pot', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'moka_pot', equipmentType: 'grinder', compatible: true },
  // Cold Brew
  { brewMethod: 'cold_brew', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'mesh_filter', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'cold_brew', equipmentType: 'grinder', compatible: true },
  // Siphon
  { brewMethod: 'siphon', equipmentType: 'immersion_brewer', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'scale_accessory', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'thermometer', compatible: true },
  { brewMethod: 'siphon', equipmentType: 'kettle', compatible: true },
];

/** Demo user accounts with preferences. */
export const userSeedData = [
  {
    email: 'alice@example.com',
    username: 'alice',
    displayName: 'Alice Brewer',
    bio: 'Espresso enthusiast from Portland',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'coffee' },
  },
  {
    email: 'bob@example.com',
    username: 'bob',
    displayName: 'Bob Barista',
    bio: 'V60 lover and specialty coffee nerd',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'dark' },
  },
  {
    email: 'charlie@example.com',
    username: 'charlie',
    displayName: 'Charlie Press',
    bio: 'French press aficionado from Seattle',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'coffee' },
  },
  {
    email: 'diana@example.com',
    username: 'diana',
    displayName: 'Diana Turkish',
    bio: 'Traditional coffee lover from Istanbul',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'dark' },
  },
  {
    email: 'evan@example.com',
    username: 'evan',
    displayName: 'Evan ColdBrew',
    bio: 'Specialty coffee experimenter',
    onboardingCompleted: true,
    preferences: { unitSystem: 'metric', theme: 'light' },
  },
];

/** User-created equipment entries (non-catalog). */
export const equipmentSeedData = [
  {
    name: 'Bottomless Portafilter 58mm',
    type: 'portafilter',
    brand: 'Lelit',
    createdByUsername: 'alice',
  },
  {
    name: 'IMS H24 18g',
    type: 'basket',
    brand: 'IMS',
    createdByUsername: 'alice',
  },
  {
    name: 'Normcore 58.5mm Spring Tamper',
    type: 'tamper',
    brand: 'Normcore',
    createdByUsername: 'alice',
  },
  {
    name: 'Metal Puck Screen 58.5mm',
    type: 'puck_screen',
    brand: 'Sieve',
    createdByUsername: 'alice',
  },
  {
    name: 'Fellow Stagg EKG',
    type: 'kettle',
    brand: 'Fellow',
    createdByUsername: 'bob',
  },
  {
    name: 'Hario V60 Paper Filter 02',
    type: 'paper_filter',
    brand: 'Hario',
    createdByUsername: 'bob',
  },
  {
    name: 'Acaia Lunar',
    type: 'scale_accessory',
    brand: 'Acaia',
    description: 'High-precision espresso scale',
    createdByUsername: 'alice',
  },
  {
    name: 'Bodum Chambord French Press',
    type: 'mesh_filter',
    brand: 'Bodum',
    description: 'Classic 8-cup French press',
    createdByUsername: 'charlie',
  },
  {
    name: 'Beko Turkish Coffee Pot',
    type: 'cezve',
    brand: 'Beko',
    description: 'Electric copper cezve',
    createdByUsername: 'diana',
  },
  {
    name: 'Hario Drip Scale',
    type: 'scale_accessory',
    brand: 'Hario',
    description: 'Pour-over scale with timer',
    createdByUsername: 'evan',
  },
];

/** Coffee vendor/roaster entries. */
export const vendorSeedData = [
  {
    name: 'Heart Coffee Roasters',
    website: 'https://heartroasters.com',
    description: 'Portland-based specialty coffee roaster',
  },
  {
    name: 'Counter Culture Coffee',
    website: 'https://counterculturecoffee.com',
    description: 'Durham-based sustainable roaster',
  },
  {
    name: 'Kurukahveci Mehmet Efendi',
    website: 'https://mehmetefendi.com',
    description: 'Historic Turkish coffee roaster from Istanbul',
  },
  {
    name: 'Stumptown Coffee Roasters',
    website: 'https://stumptowncoffee.com',
    description: 'Portland-based pioneer of third-wave coffee',
  },
  {
    name: 'Blue Bottle Coffee',
    website: 'https://bluebottlecoffee.com',
    description: 'Oakland-based specialty coffee roaster known for freshness',
  },
  {
    name: 'Intelligentsia Coffee',
    website: 'https://intelligentsiacoffee.com',
    description: 'Chicago-based direct trade specialty roaster',
  },
  {
    name: 'Onyx Coffee Lab',
    website: 'https://onyxcoffeelab.com',
    description: 'Arkansas-based award-winning specialty roaster',
  },
];

/** Coffee bean entries linked to vendors and users. */
export const beanSeedData = [
  {
    name: 'Heart Ethiopia Yirgacheffe',
    brand: 'Heart',
    vendorName: 'Heart Coffee Roasters',
    roaster: 'Heart Coffee Roasters',
    roastLevel: 'light',
    processing: 'washed',
    origin: 'Ethiopia, Yirgacheffe',
    userUsername: 'alice',
  },
  {
    name: 'Counter Culture Big Trouble',
    brand: 'Counter Culture',
    vendorName: 'Counter Culture Coffee',
    roaster: 'Counter Culture Coffee',
    roastLevel: 'medium',
    processing: 'natural',
    origin: 'Brazil, Minas Gerais',
    userUsername: 'charlie',
  },
  {
    name: 'Mehmet Efendi Turkish Blend',
    brand: 'Mehmet Efendi',
    vendorName: 'Kurukahveci Mehmet Efendi',
    roaster: 'Kurukahveci Mehmet Efendi',
    roastLevel: 'dark',
    processing: 'washed',
    origin: 'Turkey, Brazil blend',
    userUsername: 'diana',
  },
  {
    name: 'Counter Culture Fast Forward',
    brand: 'Counter Culture',
    vendorName: 'Counter Culture Coffee',
    roaster: 'Counter Culture Coffee',
    roastLevel: 'medium',
    processing: 'washed',
    origin: 'Colombia, Huila',
    userUsername: 'evan',
  },
  {
    name: 'Intelligentsia Kenya Nyeri',
    brand: 'Intelligentsia',
    vendorName: 'Intelligentsia Coffee',
    roaster: 'Intelligentsia Coffee',
    roastLevel: 'light',
    processing: 'washed',
    origin: 'Kenya, Nyeri',
    userUsername: 'bob',
  },
  {
    name: 'Onyx Coffee Lab Colombia Urrao',
    brand: 'Onyx Coffee Lab',
    vendorName: 'Onyx Coffee Lab',
    roaster: 'Onyx Coffee Lab',
    roastLevel: 'light',
    processing: 'washed',
    origin: 'Colombia, Urrao',
    userUsername: 'alice',
  },
  {
    name: 'Heart Coffee El Salvador Pacamara',
    brand: 'Heart',
    vendorName: 'Heart Coffee Roasters',
    roaster: 'Heart Coffee Roasters',
    roastLevel: 'medium',
    processing: 'honey',
    origin: 'El Salvador, Santa Ana',
    userUsername: 'bob',
  },
  {
    name: 'Blue Bottle Jamaica Blue Mountain',
    brand: 'Blue Bottle',
    vendorName: 'Blue Bottle Coffee',
    roaster: 'Blue Bottle Coffee',
    roastLevel: 'medium',
    processing: 'washed',
    origin: 'Jamaica, Blue Mountain',
    userUsername: 'charlie',
  },
  {
    name: 'Stumptown Ethiopia Guji Kurume',
    brand: 'Stumptown',
    vendorName: 'Stumptown Coffee Roasters',
    roaster: 'Stumptown Coffee Roasters',
    roastLevel: 'light',
    processing: 'natural',
    origin: 'Ethiopia, Guji',
    userUsername: 'diana',
  },
  {
    name: 'Onyx Coffee Lab El Salvador Bernardina',
    brand: 'Onyx Coffee Lab',
    vendorName: 'Onyx Coffee Lab',
    roaster: 'Onyx Coffee Lab',
    roastLevel: 'light',
    processing: 'washed',
    origin: 'El Salvador, Ahuachapán',
    userUsername: 'evan',
  },
  {
    name: 'Intelligentsia Costa Rica Villa Sarchi',
    brand: 'Intelligentsia',
    vendorName: 'Intelligentsia Coffee',
    roaster: 'Intelligentsia Coffee',
    roastLevel: 'medium',
    processing: 'honey',
    origin: 'Costa Rica, Tarrazú',
    userUsername: 'bob',
  },
  {
    name: 'Blue Bottle Yemen Mokha',
    brand: 'Blue Bottle',
    vendorName: 'Blue Bottle Coffee',
    roaster: 'Blue Bottle Coffee',
    roastLevel: 'dark',
    processing: 'natural',
    origin: 'Yemen, Sanaa',
    userUsername: 'diana',
  },
  {
    name: 'Stumptown Brazil Maragogype',
    brand: 'Stumptown',
    vendorName: 'Stumptown Coffee Roasters',
    roaster: 'Stumptown Coffee Roasters',
    roastLevel: 'medium',
    processing: 'natural',
    origin: 'Brazil, Minas Gerais',
    userUsername: 'charlie',
  },
  {
    name: 'Heart Coffee Colombia Pink Bourbon',
    brand: 'Heart',
    vendorName: 'Heart Coffee Roasters',
    roaster: 'Heart Coffee Roasters',
    roastLevel: 'light',
    processing: 'anaerobic',
    origin: 'Colombia, Huila',
    userUsername: 'alice',
  },
  {
    name: 'Counter Culture Colombia Castillo',
    brand: 'Counter Culture',
    vendorName: 'Counter Culture Coffee',
    roaster: 'Counter Culture Coffee',
    roastLevel: 'medium',
    processing: 'washed',
    origin: 'Colombia, Huila',
    userUsername: 'evan',
  },
];

/** Full recipe seed data with versions, taste notes, equipment, and photos. */
export const recipeSeedData = [
  {
    slug: 'alices-signature-espresso',
    title: "Alice's Signature Espresso",
    authorUsername: 'alice',
    coffeeVarietyName: 'Typica',
    visibility: 'public',
    likeCount: 5,
    commentCount: 2,
    forkCount: 1,
    featured: true,
    version: {
      productName: 'Heart Ethiopia Yirgacheffe',
      coffeeBrand: 'Heart',
      coffeeProcessing: 'washed',
      vendorName: 'Heart Coffee Roasters',
      roastDate: '2026-03-15',
      packageOpenDate: '2026-04-01',
      grindDate: '2026-04-10',
      brewDate: '2026-04-15',
      brewMethod: 'espresso_machine',
      drinkType: 'espresso',
      brewerDetails: 'Lelit Mara X',
      grinder: 'Lelit Fred',
      grindSize: '12',
      groundWeightGrams: 18,
      extractionTimeSeconds: 28,
      preInfusionTimeSeconds: 5,
      extractionVolumeMl: 36,
      temperatureCelsius: 93,
      tds: 9.5,
      brewRatio: 2.0,
      flowRate: 1.29,
      personalNotes: 'Beautiful sweet shot with floral notes and a honey finish.',
      preparationNotes:
        '1. Preheat the machine and portafilter for 10 minutes.\n2. Dose 18g of coffee into the basket.\n3. Distribute evenly and tamp with 15kg pressure.\n4. Lock in the portafilter and start extraction immediately.\n5. Aim for 36g out in 25-30 seconds.\n6. Serve in a preheated cup.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Rocket Espresso Appartamento',
      'Eureka Mignon Specialità',
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Normcore 58.5mm Spring Tamper',
      'Metal Puck Screen 58.5mm',
      'Acaia Lunar',
    ],
    tasteNotes: [
      { name: 'Raspberry', intensity: 2 },
      { name: 'Dark chocolate', intensity: 3 },
      { name: 'Rose', intensity: 1 },
      { name: 'Caramelized', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefad?w=800',
        alt: 'Espresso shot with crema',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'bobs-morning-v60',
    title: "Bob's Morning V60",
    authorUsername: 'bob',
    coffeeVarietyName: 'Bourbon',
    visibility: 'public',
    likeCount: 3,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Heart Ethiopia Yirgacheffe',
      coffeeBrand: 'Heart',
      coffeeProcessing: 'washed',
      vendorName: 'Heart Coffee Roasters',
      roastDate: '2026-03-15',
      packageOpenDate: '2026-03-22',
      grindDate: '2026-04-12',
      brewDate: '2026-04-12',
      brewMethod: 'v60',
      drinkType: 'pour_over',
      brewerDetails: 'Hario V60 02',
      grinder: 'Baratza Encore',
      grindSize: '20',
      groundWeightGrams: 15,
      extractionTimeSeconds: 210,
      extractionVolumeMl: 250,
      temperatureCelsius: 96,
      tds: 1.35,
      brewRatio: 16.67,
      flowRate: 1.19,
      personalNotes: 'Clean, bright cup. Great morning brew.',
      preparationNotes:
        '1. Rinse the paper filter with hot water and discard.\n2. Add 15g of medium-fine ground coffee.\n3. Bloom with 30g water for 30 seconds.\n4. Pour remaining water in slow circles to 250g total.\n5. Let drain completely.\n6. Serve immediately.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'rocket',
    },
    equipmentNames: [
      'Hario V60 02 Ceramic',
      'Hario V60 Paper Filter 02',
      'Fellow Stagg EKG',
      'Acaia Pearl S',
    ],
    tasteNotes: [
      { name: 'Jasmine', intensity: 2 },
      { name: 'Cinnamon', intensity: 3 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        alt: 'V60 pour over',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'charlies-french-press-classic',
    title: "Charlie's French Press Classic",
    authorUsername: 'charlie',
    coffeeVarietyName: 'Gesha / Geisha',
    visibility: 'public',
    likeCount: 4,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Counter Culture Big Trouble',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'natural',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-02-10',
      packageOpenDate: '2026-02-20',
      grindDate: '2026-04-05',
      brewDate: '2026-04-05',
      brewMethod: 'french_press',
      drinkType: 'french_press',
      brewerDetails: 'Bodum Chambord 8-cup',
      grinder: 'Comandante C40',
      grindSize: '28',
      groundWeightGrams: 30,
      extractionTimeSeconds: 240,
      extractionVolumeMl: 500,
      temperatureCelsius: 94,
      brewRatio: 16.67,
      flowRate: 2.08,
      personalNotes: 'Full-bodied, rich cup with chocolatey depth.',
      preparationNotes:
        '1. Preheat the press with hot water.\n2. Add 30g coarse ground coffee.\n3. Pour 500ml water at 94C.\n4. Stir gently and place lid without pressing.\n5. Steep for 4 minutes.\n6. Press slowly and serve.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'thumbsup',
    },
    equipmentNames: [
      'French Press (generic category) Bodum Chambord (1 L)',
      'Bodum Chambord French Press',
      'Acaia Lunar',
      'Fellow Stagg EKG Pro',
      'Comandante C40 MK4',
    ],
    tasteNotes: [
      { name: 'Dark chocolate', intensity: 3 },
      { name: 'Hazelnut', intensity: 2 },
      { name: 'Honey', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
        alt: 'French press coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'dianas-turkish-delight',
    title: "Diana's Turkish Delight",
    authorUsername: 'diana',
    coffeeVarietyName: 'Ethiopian Heirloom / Landrace',
    visibility: 'public',
    likeCount: 6,
    commentCount: 2,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Mehmet Efendi Turkish Blend',
      coffeeBrand: 'Mehmet Efendi',
      coffeeProcessing: 'washed',
      vendorName: 'Kurukahveci Mehmet Efendi',
      roastDate: '2026-01-15',
      packageOpenDate: '2026-02-01',
      grindDate: '2026-04-08',
      brewDate: '2026-04-08',
      brewMethod: 'turkish_coffee',
      drinkType: 'turkish_coffee',
      brewerDetails: 'Beko Electric Cezve',
      grinder: 'Manual Turkish Grinder',
      grindSize: 'powder',
      groundWeightGrams: 10,
      extractionTimeSeconds: 180,
      extractionVolumeMl: 80,
      temperatureCelsius: 88,
      brewRatio: 8.0,
      flowRate: 0.44,
      personalNotes: 'Rich, thick foam. Best enjoyed with a piece of Turkish delight.',
      preparationNotes:
        '1. Add 10g finely ground coffee and 80ml cold water to cezve.\n2. Add sugar to taste if desired.\n3. Stir well before heating.\n4. Heat slowly over low flame.\n5. Remove just before boiling when foam rises.\n6. Pour into a small cup and let grounds settle.',
      isFavourite: true,
      rating: 10,
      emojiTag: 'fire',
    },
    equipmentNames: ['Beko Turkish Coffee Pot', 'Hario Drip Scale', 'Comandante C40 MK4'],
    tasteNotes: [
      { name: 'Clove', intensity: 3 },
      { name: 'Cinnamon', intensity: 2 },
      { name: 'Tobacco', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        alt: 'Turkish coffee in cezve',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'evans-iced-latte',
    title: "Evan's Iced Latte",
    authorUsername: 'evan',
    coffeeVarietyName: 'Caturra',
    visibility: 'public',
    likeCount: 7,
    commentCount: 1,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Counter Culture Fast Forward',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'washed',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-03-01',
      packageOpenDate: '2026-03-10',
      grindDate: '2026-04-10',
      brewDate: '2026-04-10',
      brewMethod: 'espresso_machine',
      drinkType: 'latte',
      brewerDetails: 'Breville Barista Express',
      grinder: 'Built-in conical burr',
      grindSize: '15',
      groundWeightGrams: 18,
      extractionTimeSeconds: 25,
      extractionVolumeMl: 36,
      temperatureCelsius: 92,
      brewRatio: 2.0,
      flowRate: 1.44,
      personalNotes: 'Refreshing summer drink with smooth espresso and cold milk over ice.',
      preparationNotes:
        '1. Fill a tall glass with ice cubes.\n2. Pull a double espresso shot (18g in, 36g out).\n3. Pour 200ml cold whole milk over the ice.\n4. Pour the hot espresso over the milk.\n5. Stir gently and serve with a straw.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'rocket',
    },
    equipmentNames: [
      'Breville (Sage in EU) Dual Boiler',
      'Niche Niche Zero',
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Normcore 58.5mm Spring Tamper',
      'Metal Puck Screen 58.5mm',
      'Acaia Lunar',
    ],
    additionalPreparations: [
      {
        name: 'Whole milk',
        type: 'milk',
        inputAmount: '200ml',
        preparationType: 'cold',
        sortOrder: 0,
      },
    ],
    tasteNotes: [
      { name: 'Vanilla', intensity: 2 },
      { name: 'Caramelized', intensity: 2 },
      { name: 'Dark chocolate', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
        alt: 'Iced latte in glass',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'evans-affogato',
    title: "Evan's Affogato",
    authorUsername: 'evan',
    coffeeVarietyName: 'Catuaí',
    visibility: 'public',
    likeCount: 8,
    commentCount: 2,
    forkCount: 1,
    featured: true,
    version: {
      productName: 'Counter Culture Fast Forward',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'washed',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-03-01',
      packageOpenDate: '2026-03-10',
      grindDate: '2026-04-11',
      brewDate: '2026-04-11',
      brewMethod: 'espresso_machine',
      drinkType: 'espresso',
      brewerDetails: 'Breville Barista Express',
      grinder: 'Built-in conical burr',
      grindSize: '14',
      groundWeightGrams: 18,
      extractionTimeSeconds: 26,
      extractionVolumeMl: 36,
      temperatureCelsius: 93,
      brewRatio: 2.0,
      flowRate: 1.38,
      personalNotes: 'Heavenly combination of hot espresso and cold vanilla ice cream.',
      preparationNotes:
        '1. Place one scoop of vanilla ice cream in a small bowl.\n2. Pull a fresh espresso shot (18g in, 36g out).\n3. Pour the hot espresso directly over the ice cream.\n4. Serve immediately with a small spoon.',
      isFavourite: true,
      rating: 10,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'La Marzocco Linea Mini',
      'Baratza Encore ESP',
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Normcore 58.5mm Spring Tamper',
      'Metal Puck Screen 58.5mm',
      'Acaia Lunar',
    ],
    additionalPreparations: [
      {
        name: 'Vanilla ice cream',
        type: 'other',
        inputAmount: '1 scoop',
        preparationType: 'cold',
        sortOrder: 0,
      },
    ],
    tasteNotes: [
      { name: 'Vanilla', intensity: 3 },
      { name: 'Caramelized', intensity: 2 },
      { name: 'Dark chocolate', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800',
        alt: 'Affogato with ice cream',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'chiroso-espresso-delight',
    title: "Alice's Chiroso Espresso Delight",
    authorUsername: 'alice',
    coffeeVarietyName: 'Chiroso',
    visibility: 'public',
    likeCount: 4,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Onyx Coffee Lab Colombia Urrao',
      coffeeBrand: 'Onyx Coffee Lab',
      coffeeProcessing: 'washed',
      vendorName: 'Onyx Coffee Lab',
      roastDate: '2026-03-10',
      packageOpenDate: '2026-03-20',
      grindDate: '2026-04-12',
      brewDate: '2026-04-12',
      brewMethod: 'espresso_machine',
      drinkType: 'espresso',
      brewerDetails: 'Decent Espresso DE1Pro',
      grinder: 'Eureka Mignon Specialità',
      grindSize: '11',
      groundWeightGrams: 18,
      extractionTimeSeconds: 27,
      preInfusionTimeSeconds: 6,
      extractionVolumeMl: 36,
      temperatureCelsius: 94,
      tds: 9.2,
      brewRatio: 2.0,
      flowRate: 1.33,
      personalNotes: 'Stunning clarity and jasmine notes from the Chiroso.',
      preparationNotes:
        '1. Preheat the DE1Pro for 15 minutes.\n2. Dose 18g into the basket.\n3. Distribute and tamp evenly.\n4. Start extraction with 6s pre-infusion.\n5. Aim for 36g out in 25-30s.\n6. Serve immediately.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Decent Espresso DE1Pro',
      'Eureka Mignon Specialità',
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Normcore 58.5mm Spring Tamper',
      'Metal Puck Screen 58.5mm',
      'Acaia Lunar (2021)',
    ],
    tasteNotes: [
      { name: 'Raspberry', intensity: 2 },
      { name: 'Dark chocolate', intensity: 3 },
      { name: 'Honey', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefad?w=800',
        alt: 'Espresso shot with crema',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'pink-bourbon-moka-pot',
    title: "Alice's Pink Bourbon Moka Pot",
    authorUsername: 'alice',
    coffeeVarietyName: 'Pink Bourbon',
    visibility: 'public',
    likeCount: 3,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Heart Coffee Colombia Pink Bourbon',
      coffeeBrand: 'Heart',
      coffeeProcessing: 'anaerobic',
      vendorName: 'Heart Coffee Roasters',
      roastDate: '2026-02-15',
      packageOpenDate: '2026-02-25',
      grindDate: '2026-04-13',
      brewDate: '2026-04-13',
      brewMethod: 'moka_pot',
      drinkType: 'espresso',
      brewerDetails: 'Bialetti Moka Express (6-cup)',
      grinder: '1Zpresso JX-Pro S',
      grindSize: '18',
      groundWeightGrams: 20,
      extractionTimeSeconds: 240,
      extractionVolumeMl: 120,
      temperatureCelsius: 90,
      brewRatio: 6.0,
      flowRate: 0.5,
      personalNotes: 'Beautifully sweet and floral from the Pink Bourbon.',
      preparationNotes:
        '1. Fill bottom chamber with 120ml filtered water.\n2. Grind 20g coffee to medium-fine.\n3. Fill basket without tamping.\n4. Assemble and place on medium heat.\n5. Remove from heat when coffee starts to bubble.\n6. Serve immediately.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'rocket',
    },
    equipmentNames: [
      'Bialetti Moka Express (6-cup)',
      'Acaia Pearl S',
      '1Zpresso JX-Pro S',
    ],
    tasteNotes: [
      { name: 'Jasmine', intensity: 3 },
      { name: 'Peach', intensity: 2 },
      { name: 'Sweet', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        alt: 'Moka pot coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'sl28-morning-v60',
    title: "Bob's SL28 Morning V60",
    authorUsername: 'bob',
    coffeeVarietyName: 'SL28',
    visibility: 'public',
    likeCount: 5,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Intelligentsia Kenya Nyeri',
      coffeeBrand: 'Intelligentsia',
      coffeeProcessing: 'washed',
      vendorName: 'Intelligentsia Coffee',
      roastDate: '2026-03-20',
      packageOpenDate: '2026-03-27',
      grindDate: '2026-04-14',
      brewDate: '2026-04-14',
      brewMethod: 'v60',
      drinkType: 'pour_over',
      brewerDetails: 'Hario V60 02 Ceramic',
      grinder: 'Fellow Ode Gen 2',
      grindSize: '22',
      groundWeightGrams: 16,
      extractionTimeSeconds: 195,
      extractionVolumeMl: 260,
      temperatureCelsius: 96,
      tds: 1.42,
      brewRatio: 16.25,
      flowRate: 1.33,
      personalNotes: 'Bright blackcurrant acidity. Perfect morning cup.',
      preparationNotes:
        '1. Rinse V60 filter with hot water.\n2. Add 16g ground coffee.\n3. Bloom with 40g water for 35 seconds.\n4. Pour in slow spirals to 260g total.\n5. Let drain completely.\n6. Swirl and serve.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'rocket',
    },
    equipmentNames: [
      'Hario V60 02 Ceramic',
      'Hario V60 Paper Filter 02',
      'Fellow Stagg EKG Pro',
      'Acaia Pearl S',
    ],
    tasteNotes: [
      { name: 'Blackberry', intensity: 3 },
      { name: 'Citrus fruit', intensity: 2 },
      { name: 'Berry', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        alt: 'V60 pour over',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'pacamara-chemex-brew',
    title: "Bob's Pacamara Chemex Brew",
    authorUsername: 'bob',
    coffeeVarietyName: 'Pacamara',
    visibility: 'public',
    likeCount: 4,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Heart Coffee El Salvador Pacamara',
      coffeeBrand: 'Heart',
      coffeeProcessing: 'honey',
      vendorName: 'Heart Coffee Roasters',
      roastDate: '2026-02-20',
      packageOpenDate: '2026-03-01',
      grindDate: '2026-04-14',
      brewDate: '2026-04-14',
      brewMethod: 'chemex',
      drinkType: 'pour_over',
      brewerDetails: 'Chemex 6-Cup Classic',
      grinder: 'Baratza Virtuoso+',
      grindSize: '24',
      groundWeightGrams: 25,
      extractionTimeSeconds: 270,
      extractionVolumeMl: 400,
      temperatureCelsius: 95,
      tds: 1.28,
      brewRatio: 16.0,
      flowRate: 1.48,
      personalNotes: 'Elegant and clean with floral complexity.',
      preparationNotes:
        '1. Rinse Chemex filter thoroughly with hot water.\n2. Add 25g medium-coarse ground coffee.\n3. Bloom with 50g water for 45 seconds.\n4. Pour slowly in circles to 400g total.\n5. Allow to drain completely.\n6. Serve in warmed cups.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'thumbsup',
    },
    equipmentNames: [
      'Chemex 6-Cup Classic',
      'Hario V60 Paper Filter 02',
      'Brewista Artisan Variable Temp Gooseneck',
      'Timemore Black Mirror Basic+',
    ],
    tasteNotes: [
      { name: 'Floral', intensity: 2 },
      { name: 'Dark chocolate', intensity: 3 },
      { name: 'Herb-like', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1514066558159-fc8c737ef259?w=800',
        alt: 'Chemex brew',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'villa-sarchi-drip-coffee',
    title: "Bob's Villa Sarchi Drip Coffee",
    authorUsername: 'bob',
    coffeeVarietyName: 'Villa Sarchi (Villalobos)',
    visibility: 'public',
    likeCount: 3,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Intelligentsia Costa Rica Villa Sarchi',
      coffeeBrand: 'Intelligentsia',
      coffeeProcessing: 'honey',
      vendorName: 'Intelligentsia Coffee',
      roastDate: '2026-03-05',
      packageOpenDate: '2026-03-12',
      grindDate: '2026-04-14',
      brewDate: '2026-04-14',
      brewMethod: 'drip_coffee',
      drinkType: 'pour_over',
      brewerDetails: 'Technivorm Moccamaster KBG 741',
      grinder: 'Fellow Ode Gen 2',
      grindSize: '21',
      groundWeightGrams: 40,
      extractionTimeSeconds: 300,
      extractionVolumeMl: 600,
      temperatureCelsius: 94,
      brewRatio: 15.0,
      flowRate: 2.0,
      personalNotes: 'Reliable daily brew with fruity sweetness.',
      preparationNotes:
        '1. Insert paper filter and rinse.\n2. Add 40g medium ground coffee.\n3. Fill reservoir with 600ml filtered water.\n4. Start the brewer and wait for completion.\n5. Swirl carafe gently before serving.',
      isFavourite: false,
      rating: 8,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Technivorm Moccamaster KBG 741',
      'Hario V60 Paper Filter 02',
      'Hario Drip Scale',
      'Fellow Ode Gen 2',
    ],
    tasteNotes: [
      { name: 'Apple', intensity: 2 },
      { name: 'Caramelized', intensity: 3 },
      { name: 'Brown sugar', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
        alt: 'Drip coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'blue-mountain-cold-brew',
    title: "Charlie's Blue Mountain Cold Brew",
    authorUsername: 'charlie',
    coffeeVarietyName: 'Blue Mountain',
    visibility: 'public',
    likeCount: 4,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Blue Bottle Jamaica Blue Mountain',
      coffeeBrand: 'Blue Bottle',
      coffeeProcessing: 'washed',
      vendorName: 'Blue Bottle Coffee',
      roastDate: '2026-01-20',
      packageOpenDate: '2026-02-01',
      grindDate: '2026-04-12',
      brewDate: '2026-04-13',
      brewMethod: 'cold_brew',
      drinkType: 'cold_brew',
      brewerDetails: 'Toddy Cold Brew System',
      grinder: 'Mahlkönig E65S GbW',
      grindSize: '35',
      groundWeightGrams: 100,
      extractionTimeSeconds: 43200,
      extractionVolumeMl: 500,
      temperatureCelsius: 20,
      brewRatio: 5.0,
      flowRate: 0.01,
      personalNotes: 'Incredibly smooth with no bitterness. Worth the wait.',
      preparationNotes:
        '1. Coarse grind 100g Blue Mountain coffee.\n2. Add ground coffee to Toddy system.\n3. Pour 500ml cold filtered water slowly.\n4. Steep at room temperature for 12 hours.\n5. Drain and filter into a clean container.\n6. Serve over ice with a splash of water if desired.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'rocket',
    },
    equipmentNames: [
      'Toddy Cold Brew System',
      'Bodum Chambord French Press',
      'Timemore Black Mirror Basic+',
      'Mahlkönig E65S GbW',
    ],
    tasteNotes: [
      { name: 'Sweet', intensity: 2 },
      { name: 'Honey', intensity: 2 },
      { name: 'Fresh', intensity: 1 },
      { name: 'Chocolate', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
        alt: 'Cold brew coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'maragogipe-french-press',
    title: "Charlie's Maragogipe French Press",
    authorUsername: 'charlie',
    coffeeVarietyName: 'Maragogipe (Maragogype)',
    visibility: 'public',
    likeCount: 3,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Stumptown Brazil Maragogype',
      coffeeBrand: 'Stumptown',
      coffeeProcessing: 'natural',
      vendorName: 'Stumptown Coffee Roasters',
      roastDate: '2026-02-25',
      packageOpenDate: '2026-03-05',
      grindDate: '2026-04-11',
      brewDate: '2026-04-11',
      brewMethod: 'french_press',
      drinkType: 'french_press',
      brewerDetails: 'French Press (generic category) Bodum Chambord (1 L)',
      grinder: 'Niche Niche Zero',
      grindSize: '30',
      groundWeightGrams: 32,
      extractionTimeSeconds: 240,
      extractionVolumeMl: 500,
      temperatureCelsius: 94,
      brewRatio: 15.63,
      flowRate: 2.08,
      personalNotes: 'Big beans, big body. Low acidity and very sweet.',
      preparationNotes:
        '1. Preheat the press with hot water.\n2. Add 32g coarse ground coffee.\n3. Pour 500ml water at 94C.\n4. Stir gently and place lid.\n5. Steep for 4 minutes.\n6. Press slowly and pour immediately.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'thumbsup',
    },
    equipmentNames: [
      'French Press (generic category) Bodum Chambord (1 L)',
      'Bodum Chambord French Press',
      'Acaia Lunar (2021)',
      'Fellow Stagg EKG (standard)',
      'Niche Niche Zero',
    ],
    tasteNotes: [
      { name: 'Musty/Earthy', intensity: 2 },
      { name: 'Sweet', intensity: 2 },
      { name: 'Cocoa', intensity: 3 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1517701551507-6e8e4f2f7e2d?w=800',
        alt: 'French press coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'kurume-siphon-experience',
    title: "Diana's Kurume Siphon Experience",
    authorUsername: 'diana',
    coffeeVarietyName: 'Kurume',
    visibility: 'public',
    likeCount: 5,
    commentCount: 0,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Stumptown Ethiopia Guji Kurume',
      coffeeBrand: 'Stumptown',
      coffeeProcessing: 'natural',
      vendorName: 'Stumptown Coffee Roasters',
      roastDate: '2026-03-15',
      packageOpenDate: '2026-03-22',
      grindDate: '2026-04-15',
      brewDate: '2026-04-15',
      brewMethod: 'siphon',
      drinkType: 'pour_over',
      brewerDetails: 'Hario Syphon 5-cup',
      grinder: 'Comandante C40 MK4',
      grindSize: '24',
      groundWeightGrams: 20,
      extractionTimeSeconds: 150,
      extractionVolumeMl: 280,
      temperatureCelsius: 93,
      brewRatio: 14.0,
      flowRate: 1.87,
      personalNotes: 'Theater and taste combined. Floral and tea-like.',
      preparationNotes:
        '1. Fill bottom chamber with 300ml water.\n2. Heat until water rises to top chamber.\n3. Add 20g medium-fine ground coffee.\n4. Stir gently and let brew for 90 seconds.\n5. Remove heat source and let draw down.\n6. Swirl and serve in warmed cups.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Hario Syphon 5-cup',
      'Acaia Pearl S',
      'Fellow Stagg EKG (standard)',
    ],
    tasteNotes: [
      { name: 'Floral', intensity: 3 },
      { name: 'Jasmine', intensity: 2 },
      { name: 'Black Tea', intensity: 2 },
      { name: 'Citrus fruit', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefad?w=800',
        alt: 'Siphon coffee brewing',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'mokka-turkish-classic',
    title: "Diana's Mokka Turkish Classic",
    authorUsername: 'diana',
    coffeeVarietyName: 'Mokka (Yemen Mokha)',
    visibility: 'public',
    likeCount: 4,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Blue Bottle Yemen Mokha',
      coffeeBrand: 'Blue Bottle',
      coffeeProcessing: 'natural',
      vendorName: 'Blue Bottle Coffee',
      roastDate: '2026-01-10',
      packageOpenDate: '2026-01-25',
      grindDate: '2026-04-15',
      brewDate: '2026-04-15',
      brewMethod: 'turkish_coffee',
      drinkType: 'turkish_coffee',
      brewerDetails: 'Demmex Copper Cezve',
      grinder: 'Comandante C40 MK4',
      grindSize: 'powder',
      groundWeightGrams: 10,
      extractionTimeSeconds: 200,
      extractionVolumeMl: 80,
      temperatureCelsius: 88,
      brewRatio: 8.0,
      flowRate: 0.4,
      personalNotes: 'Intense chocolate and spice. Traditional and rich.',
      preparationNotes:
        '1. Add 10g finely ground Mokka coffee to cezve.\n2. Add 80ml cold water and sugar if desired.\n3. Stir well before placing on heat.\n4. Heat slowly over low flame.\n5. Remove just before boiling when foam rises.\n6. Pour into a small cup and let grounds settle.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Demmex Copper Cezve',
      'Hario Drip Scale',
      'Comandante C40 MK4',
    ],
    tasteNotes: [
      { name: 'Spices', intensity: 3 },
      { name: 'Chocolate', intensity: 2 },
      { name: 'Winey', intensity: 1 },
      { name: 'Dried fruit', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        alt: 'Turkish coffee in cezve',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'castillo-kalita-wave',
    title: "Evan's Castillo Kalita Wave",
    authorUsername: 'evan',
    coffeeVarietyName: 'Castillo',
    visibility: 'public',
    likeCount: 3,
    commentCount: 0,
    forkCount: 0,
    featured: false,
    version: {
      productName: 'Counter Culture Colombia Castillo',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'washed',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-03-01',
      packageOpenDate: '2026-03-10',
      grindDate: '2026-04-16',
      brewDate: '2026-04-16',
      brewMethod: 'kalita_wave',
      drinkType: 'pour_over',
      brewerDetails: 'Kalita Wave 185 Stainless',
      grinder: 'Baratza Encore ESP',
      grindSize: '19',
      groundWeightGrams: 18,
      extractionTimeSeconds: 200,
      extractionVolumeMl: 288,
      temperatureCelsius: 95,
      tds: 1.32,
      brewRatio: 16.0,
      flowRate: 1.44,
      personalNotes: 'Balanced and sweet with mild citrus notes.',
      preparationNotes:
        '1. Rinse Kalita Wave filter with hot water.\n2. Add 18g medium-fine ground coffee.\n3. Bloom with 40g water for 30 seconds.\n4. Pour in slow pulses to 288g total.\n5. Let drain completely.\n6. Swirl and serve.',
      isFavourite: true,
      rating: 8,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Kalita Wave 185 Stainless',
      'Hario V60 Paper Filter 02',
      'Hario V60 Buono Electric',
      'Hario Drip Scale',
    ],
    tasteNotes: [
      { name: 'Sweet', intensity: 2 },
      { name: 'Brown sugar', intensity: 2 },
      { name: 'Citrus fruit', intensity: 1 },
      { name: 'Fresh', intensity: 2 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        alt: 'Kalita Wave pour over',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'bernardina-aeropress',
    title: "Evan's Bernardina AeroPress",
    authorUsername: 'evan',
    coffeeVarietyName: 'Bernardina',
    visibility: 'public',
    likeCount: 4,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Onyx Coffee Lab El Salvador Bernardina',
      coffeeBrand: 'Onyx Coffee Lab',
      coffeeProcessing: 'washed',
      vendorName: 'Onyx Coffee Lab',
      roastDate: '2026-03-05',
      packageOpenDate: '2026-03-15',
      grindDate: '2026-04-16',
      brewDate: '2026-04-16',
      brewMethod: 'aeropress',
      drinkType: 'americano',
      brewerDetails: 'AeroPress AeroPress Original',
      grinder: 'Comandante C40 MK4',
      grindSize: '16',
      groundWeightGrams: 17,
      extractionTimeSeconds: 100,
      extractionVolumeMl: 250,
      temperatureCelsius: 88,
      brewRatio: 14.71,
      flowRate: 2.5,
      personalNotes: 'Diluted to an americano. Peach and bergamot shine through.',
      preparationNotes:
        '1. Insert paper filter and rinse.\n2. Add 17g medium-fine ground coffee.\n3. Pour 220g water at 88C and stir for 10s.\n4. Insert plunger and steep for 60 seconds.\n5. Press gently for 30 seconds.\n6. Dilute with 30g hot water and serve.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'rocket',
    },
    equipmentNames: [
      'AeroPress AeroPress Original',
      'Hario V60 Paper Filter 02',
      'Acaia Lunar (2021)',
      'Fellow Stagg EKG Pro',
      'Comandante C40 MK4',
    ],
    tasteNotes: [
      { name: 'Peach', intensity: 3 },
      { name: 'Floral', intensity: 2 },
      { name: 'Honey', intensity: 2 },
      { name: 'Jasmine', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800',
        alt: 'AeroPress coffee',
        sortOrder: 0,
      },
    ],
  },
  {
    slug: 'catuai-cappuccino',
    title: "Evan's Catuai Cappuccino",
    authorUsername: 'evan',
    coffeeVarietyName: 'Catuaí',
    visibility: 'public',
    likeCount: 5,
    commentCount: 1,
    forkCount: 0,
    featured: true,
    version: {
      productName: 'Counter Culture Fast Forward',
      coffeeBrand: 'Counter Culture',
      coffeeProcessing: 'washed',
      vendorName: 'Counter Culture Coffee',
      roastDate: '2026-03-01',
      packageOpenDate: '2026-03-10',
      grindDate: '2026-04-16',
      brewDate: '2026-04-16',
      brewMethod: 'espresso_machine',
      drinkType: 'cappuccino',
      brewerDetails: 'Rancilio Silvia Pro X',
      grinder: 'Mahlkönig E65S GbW',
      grindSize: '13',
      groundWeightGrams: 18,
      extractionTimeSeconds: 27,
      preInfusionTimeSeconds: 4,
      extractionVolumeMl: 36,
      temperatureCelsius: 93,
      tds: 9.0,
      brewRatio: 2.0,
      flowRate: 1.33,
      personalNotes: 'Silky microfoam with sweet espresso base.',
      preparationNotes:
        '1. Preheat machine and portafilter.\n2. Dose 18g and tamp evenly.\n3. Extract 36g in 25-30s with 4s pre-infusion.\n4. Steam 150ml whole milk to 60C with microfoam.\n5. Pour milk into espresso creating latte art.\n6. Serve immediately.',
      isFavourite: true,
      rating: 9,
      emojiTag: 'fire',
    },
    equipmentNames: [
      'Rancilio Silvia Pro X',
      'Mahlkönig E65S GbW',
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Normcore 58.5mm Spring Tamper',
      'Metal Puck Screen 58.5mm',
      'Acaia Lunar (2021)',
    ],
    additionalPreparations: [
      {
        name: 'Whole milk',
        type: 'milk',
        inputAmount: '150ml',
        preparationType: 'steamed',
        sortOrder: 0,
      },
    ],
    tasteNotes: [
      { name: 'Vanilla', intensity: 2 },
      { name: 'Caramelized', intensity: 2 },
      { name: 'Dark chocolate', intensity: 2 },
      { name: 'Nutty', intensity: 1 },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
        alt: 'Cappuccino with latte art',
        sortOrder: 0,
      },
    ],
  },
];

/** Social graph seed data: follows, likes, favourites, ratings, comments, and badges. */
export const socialSeedData = {
  follows: [
    { followerUsername: 'bob', followingUsername: 'alice' },
    { followerUsername: 'charlie', followingUsername: 'alice' },
    { followerUsername: 'charlie', followingUsername: 'bob' },
    { followerUsername: 'diana', followingUsername: 'alice' },
    { followerUsername: 'diana', followingUsername: 'evan' },
    { followerUsername: 'evan', followingUsername: 'diana' },
    { followerUsername: 'alice', followingUsername: 'evan' },
  ],
  likes: [
    { userUsername: 'bob', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'charlie', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'charlie', recipeSlug: 'bobs-morning-v60' },
    { userUsername: 'diana', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'diana', recipeSlug: 'charlies-french-press-classic' },
    { userUsername: 'evan', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'evan', recipeSlug: 'dianas-turkish-delight' },
    { userUsername: 'alice', recipeSlug: 'evans-iced-latte' },
    { userUsername: 'bob', recipeSlug: 'evans-affogato' },
    { userUsername: 'diana', recipeSlug: 'evans-affogato' },
    { userUsername: 'bob', recipeSlug: 'chiroso-espresso-delight' },
    { userUsername: 'charlie', recipeSlug: 'chiroso-espresso-delight' },
    { userUsername: 'diana', recipeSlug: 'chiroso-espresso-delight' },
    { userUsername: 'evan', recipeSlug: 'chiroso-espresso-delight' },
    { userUsername: 'bob', recipeSlug: 'pink-bourbon-moka-pot' },
    { userUsername: 'charlie', recipeSlug: 'pink-bourbon-moka-pot' },
    { userUsername: 'diana', recipeSlug: 'pink-bourbon-moka-pot' },
    { userUsername: 'alice', recipeSlug: 'sl28-morning-v60' },
    { userUsername: 'charlie', recipeSlug: 'sl28-morning-v60' },
    { userUsername: 'diana', recipeSlug: 'sl28-morning-v60' },
    { userUsername: 'evan', recipeSlug: 'sl28-morning-v60' },
    { userUsername: 'alice', recipeSlug: 'pacamara-chemex-brew' },
    { userUsername: 'charlie', recipeSlug: 'pacamara-chemex-brew' },
    { userUsername: 'diana', recipeSlug: 'pacamara-chemex-brew' },
    { userUsername: 'evan', recipeSlug: 'pacamara-chemex-brew' },
    { userUsername: 'alice', recipeSlug: 'villa-sarchi-drip-coffee' },
    { userUsername: 'charlie', recipeSlug: 'villa-sarchi-drip-coffee' },
    { userUsername: 'diana', recipeSlug: 'villa-sarchi-drip-coffee' },
    { userUsername: 'alice', recipeSlug: 'blue-mountain-cold-brew' },
    { userUsername: 'bob', recipeSlug: 'blue-mountain-cold-brew' },
    { userUsername: 'diana', recipeSlug: 'blue-mountain-cold-brew' },
    { userUsername: 'evan', recipeSlug: 'blue-mountain-cold-brew' },
    { userUsername: 'alice', recipeSlug: 'maragogipe-french-press' },
    { userUsername: 'bob', recipeSlug: 'maragogipe-french-press' },
    { userUsername: 'diana', recipeSlug: 'maragogipe-french-press' },
    { userUsername: 'alice', recipeSlug: 'kurume-siphon-experience' },
    { userUsername: 'bob', recipeSlug: 'kurume-siphon-experience' },
    { userUsername: 'charlie', recipeSlug: 'kurume-siphon-experience' },
    { userUsername: 'evan', recipeSlug: 'kurume-siphon-experience' },
    { userUsername: 'alice', recipeSlug: 'mokka-turkish-classic' },
    { userUsername: 'bob', recipeSlug: 'mokka-turkish-classic' },
    { userUsername: 'charlie', recipeSlug: 'mokka-turkish-classic' },
    { userUsername: 'evan', recipeSlug: 'mokka-turkish-classic' },
    { userUsername: 'alice', recipeSlug: 'castillo-kalita-wave' },
    { userUsername: 'bob', recipeSlug: 'castillo-kalita-wave' },
    { userUsername: 'charlie', recipeSlug: 'castillo-kalita-wave' },
    { userUsername: 'alice', recipeSlug: 'bernardina-aeropress' },
    { userUsername: 'bob', recipeSlug: 'bernardina-aeropress' },
    { userUsername: 'charlie', recipeSlug: 'bernardina-aeropress' },
    { userUsername: 'diana', recipeSlug: 'bernardina-aeropress' },
    { userUsername: 'alice', recipeSlug: 'catuai-cappuccino' },
    { userUsername: 'bob', recipeSlug: 'catuai-cappuccino' },
    { userUsername: 'charlie', recipeSlug: 'catuai-cappuccino' },
    { userUsername: 'diana', recipeSlug: 'catuai-cappuccino' },
  ],
  favourites: [
    { userUsername: 'bob', recipeSlug: 'alices-signature-espresso' },
    { userUsername: 'charlie', recipeSlug: 'bobs-morning-v60' },
    { userUsername: 'diana', recipeSlug: 'charlies-french-press-classic' },
    { userUsername: 'evan', recipeSlug: 'dianas-turkish-delight' },
    { userUsername: 'alice', recipeSlug: 'evans-iced-latte' },
    { userUsername: 'charlie', recipeSlug: 'chiroso-espresso-delight' },
    { userUsername: 'diana', recipeSlug: 'pink-bourbon-moka-pot' },
    { userUsername: 'alice', recipeSlug: 'sl28-morning-v60' },
    { userUsername: 'evan', recipeSlug: 'pacamara-chemex-brew' },
    { userUsername: 'bob', recipeSlug: 'blue-mountain-cold-brew' },
    { userUsername: 'charlie', recipeSlug: 'kurume-siphon-experience' },
  ],
  ratings: [
    { userUsername: 'bob', recipeSlug: 'alices-signature-espresso', rating: 9 },
    { userUsername: 'charlie', recipeSlug: 'bobs-morning-v60', rating: 8 },
    { userUsername: 'diana', recipeSlug: 'charlies-french-press-classic', rating: 8 },
    { userUsername: 'evan', recipeSlug: 'dianas-turkish-delight', rating: 10 },
    { userUsername: 'alice', recipeSlug: 'evans-iced-latte', rating: 9 },
    { userUsername: 'bob', recipeSlug: 'evans-affogato', rating: 10 },
    { userUsername: 'bob', recipeSlug: 'chiroso-espresso-delight', rating: 9 },
    { userUsername: 'charlie', recipeSlug: 'pink-bourbon-moka-pot', rating: 8 },
    { userUsername: 'diana', recipeSlug: 'sl28-morning-v60', rating: 9 },
    { userUsername: 'alice', recipeSlug: 'pacamara-chemex-brew', rating: 8 },
    { userUsername: 'evan', recipeSlug: 'villa-sarchi-drip-coffee', rating: 8 },
    { userUsername: 'alice', recipeSlug: 'blue-mountain-cold-brew', rating: 9 },
    { userUsername: 'bob', recipeSlug: 'maragogipe-french-press', rating: 8 },
    { userUsername: 'evan', recipeSlug: 'kurume-siphon-experience', rating: 9 },
    { userUsername: 'charlie', recipeSlug: 'mokka-turkish-classic', rating: 8 },
    { userUsername: 'diana', recipeSlug: 'castillo-kalita-wave', rating: 8 },
    { userUsername: 'alice', recipeSlug: 'bernardina-aeropress', rating: 9 },
    { userUsername: 'charlie', recipeSlug: 'catuai-cappuccino', rating: 8 },
  ],
  comments: [
    {
      recipeSlug: 'alices-signature-espresso',
      authorUsername: 'bob',
      content: 'Amazing shot! What grinder setting are you using?',
      replies: [
        { authorUsername: 'alice', content: 'Thanks! Setting 12 on the Lelit Fred.' },
      ],
    },
    {
      recipeSlug: 'charlies-french-press-classic',
      authorUsername: 'diana',
      content: 'Love the full body of this method!',
      replies: [],
    },
    {
      recipeSlug: 'dianas-turkish-delight',
      authorUsername: 'evan',
      content: 'The foam is incredible. What sugar ratio do you use?',
      replies: [
        {
          authorUsername: 'diana',
          content: 'I prefer it unsweetened, but 1 tsp per cup is traditional.',
        },
      ],
    },
    {
      recipeSlug: 'evans-affogato',
      authorUsername: 'alice',
      content: 'This is my new favourite dessert coffee!',
      replies: [
        {
          authorUsername: 'evan',
          content: 'Glad you like it! Try it with caramel drizzle next time.',
        },
      ],
    },
    {
      recipeSlug: 'chiroso-espresso-delight',
      authorUsername: 'charlie',
      content: 'Incredible clarity from the Chiroso!',
      replies: [],
    },
    {
      recipeSlug: 'sl28-morning-v60',
      authorUsername: 'diana',
      content: 'Those blackcurrant notes are unreal.',
      replies: [],
    },
    {
      recipeSlug: 'blue-mountain-cold-brew',
      authorUsername: 'bob',
      content: 'So smooth for a cold brew.',
      replies: [],
    },
    {
      recipeSlug: 'bernardina-aeropress',
      authorUsername: 'alice',
      content: 'AeroPress really brings out the peach notes.',
      replies: [],
    },
    {
      recipeSlug: 'catuai-cappuccino',
      authorUsername: 'diana',
      content: 'Perfect foam texture!',
      replies: [
        {
          authorUsername: 'evan',
          content: 'Thanks! The Silvia Pro X makes it easy.',
        },
      ],
    },
  ],
  badges: [
    { userUsername: 'alice', badgeRule: 'first_brew' },
    { userUsername: 'bob', badgeRule: 'first_brew' },
    { userUsername: 'charlie', badgeRule: 'first_brew' },
    { userUsername: 'diana', badgeRule: 'first_brew' },
    { userUsername: 'evan', badgeRule: 'first_brew' },
  ],
};

/** User brewing setup entries with equipment slot assignments. */
export const setupSeedData = [
  {
    name: "Alice's Espresso Setup",
    userUsername: 'alice',
    brewerDetails: 'Lelit Mara X',
    grinder: 'Lelit Fred',
    equipmentNames: [
      'Bottomless Portafilter 58mm',
      'IMS H24 18g',
      'Metal Puck Screen 58.5mm',
      'Normcore 58.5mm Spring Tamper',
    ],
    isDefault: true,
  },
  {
    name: "Bob's V60 Setup",
    userUsername: 'bob',
    brewerDetails: 'Hario V60 02',
    grinder: 'Baratza Encore',
    equipmentNames: [],
    isDefault: true,
  },
  {
    name: "Charlie's French Press Setup",
    userUsername: 'charlie',
    brewerDetails: 'Bodum Chambord 8-cup',
    grinder: 'Comandante C40',
    equipmentNames: ['Bodum Chambord French Press'],
    isDefault: true,
  },
  {
    name: "Diana's Turkish Setup",
    userUsername: 'diana',
    brewerDetails: 'Beko Electric Cezve',
    grinder: 'Manual Turkish Grinder',
    equipmentNames: ['Beko Turkish Coffee Pot'],
    isDefault: true,
  },
  {
    name: "Evan's Espresso Setup",
    userUsername: 'evan',
    brewerDetails: 'Breville Barista Express',
    grinder: 'Built-in conical burr',
    equipmentNames: [],
    isDefault: true,
  },
];
