import { Hono } from 'hono';
import health from './health.ts';
import openapi from './openapi.ts';
import auth from '../modules/auth/index.ts';
import user from '../modules/user/index.ts';
import recipe from '../modules/recipe/index.ts';
import equipment from '../modules/equipment/index.ts';
import bean from '../modules/bean/index.ts';
import vendor from '../modules/vendor/index.ts';
import taste from '../modules/taste/index.ts';
import photo from '../modules/photo/index.ts';
import comment from '../modules/comment/index.ts';
import follow from '../modules/follow/index.ts';
import badge from '../modules/badge/index.ts';
import setup from '../modules/setup/index.ts';
import preference from '../modules/preference/index.ts';
import search from '../modules/search/index.ts';
import qrcode from '../modules/qrcode/index.ts';
import report from '../modules/report/index.ts';

const routes = new Hono();

routes.route('/', health);
routes.route('/', openapi);
routes.route('/api/v1/auth', auth);
routes.route('/api/v1/users', user);
routes.route('/api/v1/recipes', recipe);
routes.route('/api/v1/equipment', equipment);
routes.route('/api/v1/beans', bean);
routes.route('/api/v1/vendors', vendor);
routes.route('/api/v1/taste-notes', taste);
routes.route('/api/v1/photos', photo);
routes.route('/api/v1/comments', comment);
routes.route('/api/v1/follow', follow);
routes.route('/api/v1/badges', badge);
routes.route('/api/v1/setups', setup);
routes.route('/api/v1/preferences', preference);
routes.route('/api/v1/search', search);
routes.route('/api/v1/qrcode', qrcode);
routes.route('/api/v1/reports', report);

export default routes;